# Generated by Django 2.1.1 on 2018-09-05 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_testprogfields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestProgFields',
        ),
    ]
