# Generated by Django 2.1.1 on 2018-09-06 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('api', '0005_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideDeck',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('plus_1', models.IntegerField(default=1)),
                ('minus_1', models.IntegerField(default=1)),
                ('bival_1', models.IntegerField(default=0)),
                ('plus_2', models.IntegerField(default=1)),
                ('minus_2', models.IntegerField(default=1)),
                ('bival_2', models.IntegerField(default=0)),
                ('plus_3', models.IntegerField(default=0)),
                ('minus_3', models.IntegerField(default=0)),
                ('bival_3', models.IntegerField(default=0)),
                ('plus_4', models.IntegerField(default=0)),
                ('minus_4', models.IntegerField(default=0)),
                ('bival_4', models.IntegerField(default=0)),
                ('plus_5', models.IntegerField(default=0)),
                ('minus_5', models.IntegerField(default=0)),
                ('bival_5', models.IntegerField(default=0)),
                ('plus_6', models.IntegerField(default=0)),
                ('minus_6', models.IntegerField(default=0)),
                ('bival_6', models.IntegerField(default=0)),
            ],
        ),
    ]
