# Generated by Django 2.1.1 on 2018-09-06 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_sidedeck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidedeck',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='side_deck', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
