# Generated by Django 2.1.1 on 2018-09-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180904_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestProgFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_0', models.IntegerField(default=0)),
                ('card_1', models.IntegerField(default=0)),
                ('card_2', models.IntegerField(default=0)),
                ('card_3', models.IntegerField(default=0)),
                ('card_4', models.IntegerField(default=0)),
                ('card_5', models.IntegerField(default=0)),
                ('card_6', models.IntegerField(default=0)),
                ('card_7', models.IntegerField(default=0)),
                ('card_8', models.IntegerField(default=0)),
                ('card_9', models.IntegerField(default=0)),
                ('card_10', models.IntegerField(default=0)),
                ('card_11', models.IntegerField(default=0)),
                ('card_12', models.IntegerField(default=0)),
                ('card_13', models.IntegerField(default=0)),
                ('card_14', models.IntegerField(default=0)),
                ('card_15', models.IntegerField(default=0)),
                ('card_16', models.IntegerField(default=0)),
                ('card_17', models.IntegerField(default=0)),
            ],
        ),
    ]
