# Generated by Django 2.1.1 on 2018-09-05 21:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_delete_testprogfields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_at', models.DateTimeField(auto_now_add=True)),
                ('user_1_rank', models.IntegerField(choices=[(1, 'Mark'), (2, 'Novice'), (3, 'Hustler'), (4, 'Sharp'), (5, 'Force User')])),
                ('user_2_rank', models.IntegerField(choices=[(1, 'Mark'), (2, 'Novice'), (3, 'Hustler'), (4, 'Sharp'), (5, 'Force User')])),
                ('user_1_xp_delta', models.IntegerField()),
                ('user_2_xp_delta', models.IntegerField()),
                ('user_1', models.ForeignKey(on_delete='PROTECT', related_name='user_1', to=settings.AUTH_USER_MODEL)),
                ('user_2', models.ForeignKey(on_delete='PROTECT', related_name='user_2', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(on_delete='PROTECT', related_name='winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
