# Generated by Django 2.1.1 on 2018-09-29 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180906_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_change_profile_total_xp', 'Can change total_xp'), ('can_change_profile_rank', 'Can change rank'), ('can_change_profile_games_played', 'Can change games_played'), ('can_change_profile_games_won', 'Can change games_won'), ('can_change_profile_location', 'Can change location'), ('can_change_profile_joined', 'Can change joined date'))},
        ),
    ]
